### ISSUE TITLE
Support ~ for home dir

### ISSUE THREAD

**Issue by lespea** [stevenjack/cig#29]
In my yaml conf if I specify a path like `~/dev` I get a nil pointer panic; specifying the full path works fine.

**Comment by GeertJohan** [comment]
:+1: 
I don't think this is a bug, rather a new feature. The tilde (`~`) is normally expanded by the shell (bash, zsh, etc.). It's not a valid file path component. I would say this feature could come in handy though, I've had the need for this before. (missing `/home/geertjohan` in my cig paths caused the error fixed in #32 )
